

version: '3.8'

services:

  backend:
    image: x-corte-backend:latest
    container_name: x-corte-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
  
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    container_name: redis-bullmq
    restart: unless-stopped
    ports:
      - "10000:6379"